services:
  app:
    hostname: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: builder
    command: air
    ports:
      - 8080:8080
    volumes:
      - ./:/go/src/app
